api_platform:
    title: 'BitBag-API'
    description: 'API test'
    # Version
    version: '0.0.1'
    # Enable the docs.
    enable_docs: true

    # Enable the Swagger documentation and export.
    enable_swagger: true
    # Enable Swagger ui.
    enable_swagger_ui: true

    mapping:
        paths:
            - '%kernel.project_dir%/config/api_platform'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
