App\Entity\User:
  type: entity
  table: api_user
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
    email:
      type: string
    password:
      type: string
  oneToMany:
    post:
      targetEntity: App\Entity\Post
      mappedBy: userPost
